var annotated_dup =
[
    [ "JamesEngine", null, [
      [ "Audio", "class_james_engine_1_1_audio.html", null ],
      [ "AudioSource", "class_james_engine_1_1_audio_source.html", "class_james_engine_1_1_audio_source" ],
      [ "BoxCollider", "class_james_engine_1_1_box_collider.html", null ],
      [ "Camera", "class_james_engine_1_1_camera.html", null ],
      [ "Component", "class_james_engine_1_1_component.html", "class_james_engine_1_1_component" ],
      [ "Core", "class_james_engine_1_1_core.html", "class_james_engine_1_1_core" ],
      [ "Entity", "class_james_engine_1_1_entity.html", "class_james_engine_1_1_entity" ],
      [ "Font", "class_james_engine_1_1_font.html", null ],
      [ "GUI", "class_james_engine_1_1_g_u_i.html", null ],
      [ "Input", "class_james_engine_1_1_input.html", null ],
      [ "Keyboard", "class_james_engine_1_1_keyboard.html", null ],
      [ "Model", "class_james_engine_1_1_model.html", null ],
      [ "ModelRenderer", "class_james_engine_1_1_model_renderer.html", "class_james_engine_1_1_model_renderer" ],
      [ "Mouse", "class_james_engine_1_1_mouse.html", null ],
      [ "Resource", "class_james_engine_1_1_resource.html", null ],
      [ "Resources", "class_james_engine_1_1_resources.html", null ],
      [ "Rigidbody", "class_james_engine_1_1_rigidbody.html", "class_james_engine_1_1_rigidbody" ],
      [ "Shader", "class_james_engine_1_1_shader.html", null ],
      [ "Skybox", "class_james_engine_1_1_skybox.html", null ],
      [ "SkyboxTexture", "class_james_engine_1_1_skybox_texture.html", null ],
      [ "Sound", "class_james_engine_1_1_sound.html", null ],
      [ "Texture", "class_james_engine_1_1_texture.html", null ],
      [ "Transform", "class_james_engine_1_1_transform.html", null ],
      [ "TriangleRenderer", "class_james_engine_1_1_triangle_renderer.html", "class_james_engine_1_1_triangle_renderer" ],
      [ "Window", "class_james_engine_1_1_window.html", null ]
    ] ],
    [ "Renderer", null, [
      [ "Character", "struct_renderer_1_1_character.html", null ],
      [ "Face", "struct_renderer_1_1_face.html", null ],
      [ "Font", "class_renderer_1_1_font.html", null ],
      [ "Mesh", "class_renderer_1_1_mesh.html", null ],
      [ "Model", "class_renderer_1_1_model.html", null ],
      [ "RenderTexture", "class_renderer_1_1_render_texture.html", null ],
      [ "Shader", "class_renderer_1_1_shader.html", null ],
      [ "Texture", "class_renderer_1_1_texture.html", null ],
      [ "Vertex", "struct_renderer_1_1_vertex.html", null ]
    ] ],
    [ "Codebook", "struct_codebook.html", null ],
    [ "Collectable", "struct_collectable.html", "struct_collectable" ],
    [ "CRCscan", "struct_c_r_cscan.html", null ],
    [ "float_conv", "unionfloat__conv.html", null ],
    [ "Floor", "union_floor.html", null ],
    [ "Floor0", "struct_floor0.html", null ],
    [ "Floor1", "struct_floor1.html", null ],
    [ "Mapping", "struct_mapping.html", null ],
    [ "MappingChannel", "struct_mapping_channel.html", null ],
    [ "MenuCamera", "struct_menu_camera.html", "struct_menu_camera" ],
    [ "Mode", "struct_mode.html", null ],
    [ "Player", "struct_player.html", "struct_player" ],
    [ "ProbedPage", "struct_probed_page.html", null ],
    [ "Residue", "struct_residue.html", null ],
    [ "stb_vorbis", "structstb__vorbis.html", null ],
    [ "stb_vorbis_alloc", "structstb__vorbis__alloc.html", null ],
    [ "stb_vorbis_comment", "structstb__vorbis__comment.html", null ],
    [ "stb_vorbis_info", "structstb__vorbis__info.html", null ],
    [ "stbv__floor_ordering", "structstbv____floor__ordering.html", null ],
    [ "Timer", "class_timer.html", null ]
];