var hierarchy =
[
    [ "JamesEngine::Audio", "class_james_engine_1_1_audio.html", null ],
    [ "Renderer::Character", "struct_renderer_1_1_character.html", null ],
    [ "Codebook", "struct_codebook.html", null ],
    [ "JamesEngine::Component", "class_james_engine_1_1_component.html", [
      [ "CameraController", "struct_camera_controller.html", null ],
      [ "JamesEngine::AudioSource", "class_james_engine_1_1_audio_source.html", null ],
      [ "JamesEngine::BoxCollider", "class_james_engine_1_1_box_collider.html", null ],
      [ "JamesEngine::Camera", "class_james_engine_1_1_camera.html", null ],
      [ "JamesEngine::ModelRenderer", "class_james_engine_1_1_model_renderer.html", null ],
      [ "JamesEngine::Rigidbody", "class_james_engine_1_1_rigidbody.html", null ],
      [ "JamesEngine::Transform", "class_james_engine_1_1_transform.html", null ],
      [ "JamesEngine::TriangleRenderer", "class_james_engine_1_1_triangle_renderer.html", null ],
      [ "Player", "struct_player.html", null ]
    ] ],
    [ "JamesEngine::Core", "class_james_engine_1_1_core.html", null ],
    [ "CRCscan", "struct_c_r_cscan.html", null ],
    [ "JamesEngine::Entity", "class_james_engine_1_1_entity.html", null ],
    [ "Renderer::Face", "struct_renderer_1_1_face.html", null ],
    [ "float_conv", "unionfloat__conv.html", null ],
    [ "Floor", "union_floor.html", null ],
    [ "Floor0", "struct_floor0.html", null ],
    [ "Floor1", "struct_floor1.html", null ],
    [ "Renderer::Font", "class_renderer_1_1_font.html", null ],
    [ "JamesEngine::GUI", "class_james_engine_1_1_g_u_i.html", null ],
    [ "JamesEngine::Input", "class_james_engine_1_1_input.html", null ],
    [ "JamesEngine::Keyboard", "class_james_engine_1_1_keyboard.html", null ],
    [ "Mapping", "struct_mapping.html", null ],
    [ "MappingChannel", "struct_mapping_channel.html", null ],
    [ "Renderer::Mesh", "class_renderer_1_1_mesh.html", null ],
    [ "Mode", "struct_mode.html", null ],
    [ "Renderer::Model", "class_renderer_1_1_model.html", null ],
    [ "JamesEngine::Mouse", "class_james_engine_1_1_mouse.html", null ],
    [ "ProbedPage", "struct_probed_page.html", null ],
    [ "Renderer::RenderTexture", "class_renderer_1_1_render_texture.html", null ],
    [ "Residue", "struct_residue.html", null ],
    [ "JamesEngine::Resource", "class_james_engine_1_1_resource.html", [
      [ "JamesEngine::Font", "class_james_engine_1_1_font.html", null ],
      [ "JamesEngine::Model", "class_james_engine_1_1_model.html", null ],
      [ "JamesEngine::Shader", "class_james_engine_1_1_shader.html", null ],
      [ "JamesEngine::SkyboxTexture", "class_james_engine_1_1_skybox_texture.html", null ],
      [ "JamesEngine::Sound", "class_james_engine_1_1_sound.html", null ],
      [ "JamesEngine::Texture", "class_james_engine_1_1_texture.html", null ]
    ] ],
    [ "JamesEngine::Resources", "class_james_engine_1_1_resources.html", null ],
    [ "Renderer::Shader", "class_renderer_1_1_shader.html", null ],
    [ "JamesEngine::Skybox", "class_james_engine_1_1_skybox.html", null ],
    [ "stb_vorbis", "structstb__vorbis.html", null ],
    [ "stb_vorbis_alloc", "structstb__vorbis__alloc.html", null ],
    [ "stb_vorbis_comment", "structstb__vorbis__comment.html", null ],
    [ "stb_vorbis_info", "structstb__vorbis__info.html", null ],
    [ "stbv__floor_ordering", "structstbv____floor__ordering.html", null ],
    [ "Renderer::Texture", "class_renderer_1_1_texture.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "Renderer::Vertex", "struct_renderer_1_1_vertex.html", null ],
    [ "JamesEngine::Window", "class_james_engine_1_1_window.html", null ]
];